export const students=[
    {
      id:1,
      firstName:'Hishana',
      lastName:'Muhammed',
      department:'MCA',
      batch:2022,
      email:"hishana@gmail.com",
      contact:986464872
    },
    {
      id:2,
      firstName:'Siva',
      lastName:'Priya',
      department:'BCA',
      batch:2022,
      email:"siva@gmail.com",
      contact:986674872
    },
    {
      id:3,
      firstName:'Dilna',
      lastName:'Daison',
      department:'MCA',
      batch:2022,
      email:"dilna@gmail.com",
      contact:986464872
    },
    {
      id:4,
      firstName:'Anu',
      lastName:'Surendran',
      department:'BCA',
      batch:2022,
      email:"anu@gmail.com",
      contact:986674872
    },
    {
      id:5,
      firstName:'Mathew',
      lastName:'Boby',
      department:'IT',
      batch:2018,
      email:"mathew@gmail.com",
      contact:986674872
    },
  ]